#!/bin/sh

cd tracker
./tracker.py 192.168.0.250 3000 & > /var/log/iotp2p/tracker_3000.log
pid1=$!
./tracker.py 192.168.0.250 3001 & > /var/log/iotp2p/tracker_3001.log
pid2=$!
./tracker.py 192.168.0.250 3002 & > /var/log/iotp2p/tracker_3002.log
pid3=$!
echo Started tracker net.
cd ..
echo kill $pid1 $pid2 $pid3 > stop_iotp2p

