#!/bin/sh

cd tracker
./tracker.py 192.168.0.250 3000 &
pid1=$!
./tracker.py 192.168.0.250 3001 &
pid2=$!
./tracker.py 192.168.0.250 3002 &
pid3=$!
echo Started tracker net.
cd ..
echo kill $pid1 $pid2 $pid3 > stop_iotp2p

