#!/bin/bash
#
# Very rough installer, just provides a quick shoortcut during development to copy stuff in the right place.
#   Copyright (C) 2013 Nicola Cimmino
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see http://www.gnu.org/licenses/.


mkdir -p /usr/sbin/pynode
cp pynode.py /usr/sbin/pynode/
cp ../../modules/datagramtalk.py /usr/sbin/pynode/
cp ../../modules/iotp2p.py /usr/sbin/pynode/
cp pynodelogger /etc/init.d/

update-rc.d pynodelogger defaults
service pynodelogger restart

